#!/usr/bin/env ruby
require 'FileUtils'

def link(path, link_name)
  path = File.expand_path path
  link_name = File.expand_path link_name

  puts "linking #{link_name}..."

  if File.symlink? link_name
    puts "\tRemoving symlink..."
    FileUtils.rm link_name
  elsif File.exists? link_name
    puts "\tSkipping because a file already exists."
    return
  end

  FileUtils.ln_s(path, link_name)
end

puts "Bootstrapping Jeremy's Dotfiles..."
link "~/.dotfiles/vim/.vimrc", "~/.vimrc"
link "~/.dotfiles/git/.gitconfig", "~/.gitconfig"
link "~/.dotfiles/zsh/.zshrc", "~/.zshrc"
link "~/.dotfiles/git/.gitignore_global", "~/.gitignore_global"
link "~/.dotfiles/vim/vim", "~/.vim"

puts "done"
