tap "AlexanderWillner/tap"
tap "goreleaser/tap"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "kajabi/tap"
tap "koekeishiya/formulae"
tap "ngrok/ngrok"

brew "antibody"
brew "caddy"
brew "ctags"
brew "fish"
brew "fzf"
brew "gh"
brew "go"
brew "goreleaser-pro"
brew "hub"
brew "kajabi"
brew "lua-language-server"
brew "mas"
brew "mosh"
brew "neovim"
brew "skhd"
brew "terraform"
brew "the_silver_searcher"
brew "things.sh"
brew "tldr"
brew "tmux"
brew "yabai"

# Mac apps
cask "1password"
cask "alacritty"
cask "cheatsheet"
cask "docker"
cask "font-fira-code"
cask "monitorcontrol"
cask "ngrok/ngrok/ngrok"
cask "signal"
cask "slack"
cask "visual-studio-code"
cask "zoom"

# Mac App Store Apps
mas "Bear", id: 1091189122
mas "Things", id: 904280696
mas "Vimari", id: 1480933944
