require "os"

tap "AlexanderWillner/tap"
tap "epk/epk"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "kajabi/tap"
tap "koekeishiya/formulae"
tap "nats-io/nats-tools"
tap "ngrok/ngrok"
tap "tinygo-org/tools"
tap "knative/client"

brew "asciinema"
brew "binaryen"
brew "caddy"
brew "ctags"
brew "deno"
brew "esbuild"
brew "figlet"
brew "fish"
brew "fisher"
brew "gcc@5"
brew "gh"
brew "git"
brew "go"
brew "gotop"
brew "hey"
brew "hub"
brew "jq"
brew "k3d"
brew "kajabi"
brew "kind"
brew "kn"
brew "ko"
brew "kubectl"
brew "lazygit"
brew "llvm"
brew "lua-language-server"
brew "mas"
brew "nats-server"
brew "neovim", args: ["HEAD"]
brew "neovim-remote"
brew "neofetch"
brew "node"
brew "protobuf"
brew "python"
brew "rg"
brew "ruby@2.7"
brew "rust"
brew "rust-analyzer"
brew "starship"
brew "terraform"
brew "things.sh"
brew "tinygo"
brew "vercel-cli"
brew "viddy"
brew "watch"
brew "yabai"
brew "yaml-language-server"

if OS.mac?
  brew "skhd"

  # Mac apps
  cask "1password"
  cask "alacritty"
  cask "brave-browser"
  cask "cheatsheet"
  cask "discord"
  cask "docker"
  cask "font-fira-code-nerd-font"
  cask "font-inter"
  cask "font-sf-mono-nerd-font"
  cask "imageoptim"
  cask "kitty"
  cask "maccy"
  cask "ngrok/ngrok/ngrok"
  cask "obs"
  cask "signal"
  cask "slack"
  cask "soundsource"
  cask "visual-studio-code"
  cask "whichspace"
  cask "zoom"

  # Mac App Store Apps
  # mas "Bear", id: 1091189122
  # mas "Things", id: 904280696
end
